name: Build and Deploy
on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
jobs:
  extract-tag:
    runs-on: ubuntu-latest
    outputs:
      TAG: ${{ steps.tag.outputs.TAG }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Lift to env
        id: tag
        run: |
          echo "RAW_TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
      - name: Parse tag
        run: |
          PARSED=$(echo $RAW_TAG | sed 's/^v\(.*\)/\1/')
          echo $PARSED
      - name: Print tag
        run: |
          echo $TAG
          echo $RAW_TAG
          echo ${{ env.RAW_TAG }}
          echo ${{ env.TAG }}
  


