name: Build and Deploy
on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
jobs:
  extract-tag:
    runs-on: ubuntu-latest
    outputs:
      TAG: ${{ steps.tag.outputs.TAG }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Lift to env
        id: raw-tag
        run: |
          echo "RAW_TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
      - name: Parse tag
        id: tag
        run: |
          PARSED=$(echo $RAW_TAG | sed 's/^v\(.*\)/\1/')
          echo "TAG=$PARSED" >> $GITHUB_OUTPUT
  run-tests:
    runs-on: ubuntu-latest
    outputs:
      TEST_RESULT: ${{ steps.test.outputs.TEST_RESULT }}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Setup Maven Action
        uses: s4u/setup-maven-action@v1.13.0
        with:
          java-version: 8
          maven-version: 3.9.1
          checkout-token: ${{ github.token }}
      - name: Set up SSL keys
        run: |
          sudo apt update
          openssl s_client -showcerts -connect maven.java.net:443 < /dev/null 2> /dev/null | openssl x509 -outform PEM > maven_cert.pem
          sudo keytool -import -trustcacerts -file maven_cert.pem -alias maven-snapshot -keystore $JAVA_HOME/jre/lib/security/cacerts -storepass changeit -noprompt
      - name: Run Maven Tests
        id: test
        run: |
          cd LendARead2-AWS/LendARead2/
          # mvn clean test || OUTPUT=$? 
          echo "TEST_RESULT=${OUTPUT:-1}" >> $GITHUB_OUTPUT

  delete-tag-if-tests-failed:
    runs-on: ubuntu-latest
    needs: 
      - run-tests
      - extract-tag
    if: needs.run-tests.outputs.TEST_RESULT != '0'
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Remove tag
        run: |
          TAG_TO_RMV=v${{ needs.extract-tag.outputs.TAG }}
          echo $TAG_TO_RMV
          git push origin --delete $TAG_TO_RMV
  


