name: Build and Deploy
on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
jobs:
  extract-tag:
    runs-on: ubuntu-latest
    outputs:
      TAG: ${{ steps.tag.outputs.TAG }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Extract tag
        id: tag
        run: |
          echo "RAW_TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
          PARSED_TAG=$(echo $RAW_TAG | sed 's/^v\(.*\)/\1/')
          echo $PARSED_TAG
          echo "TAG=$PARSED_TAG" >> $GITHUB_OUTPUT
          echo "TAG=$PARSED_TAG" >> $GITHUB_ENV
      - name: Print tag
        run: |
          echo $TAG
          echo ${{ env.TAG }}
  


